name: CI

on:
  push:
    branches: [main]

env:
  BUCKET: barbershop-dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    
    - uses: actions/checkout@v2
    
    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 22.x

    - name: Install dependencies
      run: yarn install

    - name: Run tests
      run: yarn test --watchAll false --passWithNoTests

    - name: Build frontend
      run: yarn build  # Garante que a pasta build seja criada dentro de frontend

    - name: Upload filed to bucket
      run: gsutil -m rsync -R ./build gs://"$BUCKET"

    - name: Allow public access
      run: gsutil -m acl ch -R -u AllUsers:R gs://"$BUCKET"

    - name: Set Cache-Control for static files
      run: gsutil -m setmeta -h "Cache-Control:public, max-age=15768000" gs://"$BUCKET"/static/css/*.{css}

    - name: Set Cache-Control for index.html
      run: gsutil -m setmeta -h "Cache-Control:no-cache, no-store" gs://"$BUCKET"/index.html
