name: CI

on:
  push:
    branches: [main]

env:
  BUCKET: barbershop-dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 22.x

    - name: Install dependencies
      run: yarn install

    - name: Run tests
      run: yarn test --watchAll false

    - name: Build frontend
      run: yarn build  # Garante que a pasta build seja criada dentro de frontend

    - uses: google-github-actions/setup-gcloud@v0.7.0
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Upload filed to bucket
      run: gsutil -m rsync -R ./build gs://"$BUCKET"

    - name: Allow public access
      run: gsutil -m acl ch -R -u AllUsers:R gs://"$BUCKET"

    - name: Set Cache-Control for static files
      run: gsutil -m setmeta -h "Cache-Control:public, max-age=15768000" gs://"$BUCKET"/*.{png,svg,css,js}

    - name: Set Cache-Control for index.html
      run: gsutil -m setmeta -h "Cache-Control:no-cache, no-store" gs://"$BUCKET"/index.html
