name: CI

on:
  push:
    branches: [main]

env:
  BUCKET: barbershop-dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: 22.x

    - name: Install dependencies
      run: yarn install

    - name: Run tests
      run: yarn test --watchAll false --passWithNoTests

    - name: Build frontend
      run: yarn build  # Garante que a pasta build seja criada dentro de frontend

    - uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        export_environment_variables: true
        cleanup_credentials: true
        access_token_scopes: https://www.googleapis.com/auth/cloud-platform

    - name: Upload filed to bucket
      run: gsutil -m rsync -R ./build gs://"$BUCKET"

    - name: Allow public access
      run: gsutil -m acl ch -R -u AllUsers:R gs://"$BUCKET"

    - name: Set Cache-Control for static files
      run: gsutil -m setmeta -h "Cache-Control:public, max-age=15768000" gs://"$BUCKET"/*.{png,svg,css,js}

    - name: Set Cache-Control for index.html
      run: gsutil -m setmeta -h "Cache-Control:no-cache, no-store" gs://"$BUCKET"/index.html
